# http://www.appveyor.com/docs/appveyor-yml

platform: x64

image: Visual Studio 2022

clone_depth: 1

version: "{build}"

# What combinations to test
environment:
  nodejs_version: "21"

install:
- ps: Install-Product node $env:nodejs_version
- npm install

test_script:
# Output useful info for debugging
- node --version && npm --version
# We test multiple Windows shells because of prior stdout buffering issues
# filed against Grunt. https://github.com/joyent/node/issues/3584
- ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
- cmd: npm test

build: off

cache:
- node_modules -> package.json
